spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: adminDF
    url: jdbc:postgresql://localhost:5432/students
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true